import os.path
import numpy as np

def random_dnasequence(size):
    """
    Generate random sequence of DNA

    Parameters
    ----------
    size : Size of DNA in bp
      An integer between 1 and 100 000 000.

    Returns
    -------
    string
      A string corresponding to DNA sequence.

    Examples
    --------
    >>> from insilicogenome import insilicogenome
    >>> insilicogenome.random_dnasequence(10)
    Seq('GTTCTTGAT')
    """
    if ((size>= 0) and (size<= 100000000)):
        pass
    elif (size > 100000000):  # on a title line
        raise ValueError(
            "The size of the sequence to generate is greater than the maximum size of 100000000bp"
            f"The value of '{size}' is too big, it must be reduced"
        )
    else:
        assert size > 0, "Size value negatif ; this should be impossible!"
    np.random.seed(123)
    sequence = ''.join(np.random.choice(('C','G','T','A'), size ))
    return sequence

def write_fasta_genome(output, sequence):
    """
    Writes name/sequence to file in FASTA format

    Parameters
    ----------
    output : The name of the header and fasta file
      A string containing the path
    sequence : A sequence of DNA between 1 and 100 000 000bp
      A string generated by random_dnasequence

    Returns
    -------
    None

    Examples
    --------
    >>> from insilicogenome import insilicogenome
    >>> insilicogenome.write_fasta_genome(/path/genome.fasta, 'GTTCTTGAT')
    """
    # Confirm path make sens, and allow absolut path
    if os.path.isfile(output):
        raise FileExistsError
    # Raise error if not only ACTG in sequence to avoid inversion
    with open(output, 'w') as outfile:
            outfile.write(f">{output}\n{sequence}\n")